on:
  push: 
    # tags:
    #   - "v*"
    branches:
      - master
    # paths:
    #   - "**.py"
    #   - "**.blend"
  workflow_dispatch:

jobs:
  release:
    name: "Create blender addon realease when new tag is uploaded on main branch"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Create release zip
        id: prepare-release
        working-directory: ./
        env:
          GITHUB_REF: ${{env.GITHUB_REF}}
        run: python release.py


      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: ${{steps.prepare-release.outputs.tag_string}}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            kuba-addon-*.zip
          